// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

import {
  Inter,
  Crimson_Pro,
  Crimson_Text,
  Cinzel_Decorative,
} from "next/font/google";
import "./globals.css";

// 1. Definisikan tiap font ✍️
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // Buat variabel CSS
});

const crimsonPro = Crimson_Pro({
  subsets: ["latin"],
  variable: "--font-crimson-pro",
});

const crimsonText = Crimson_Text({
  weight: ["400", "600", "700"], // Pilih weight yang kamu butuhin
  subsets: ["latin"],
  variable: "--font-crimson-text",
});

const cinzelDeco = Cinzel_Decorative({
  weight: ["400", "700", "900"],
  subsets: ["latin"],
  variable: "--font-cinzel-deco",
});

export const metadata = {
  title: "Bango Parc | Your Favorite Venue",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${crimsonPro.variable} ${crimsonText.variable} ${cinzelDeco.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
